/*
 * Psiphon Access
 * Copyright (C) 2026  Psiphon Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

// Generated by tool/teleport-google/assets/stamp-build.py. Do not edit.
//
// The login page shows these so that the AGPL section 13 offer resolves to the
// build a user is actually talking to, rather than to whatever the default
// branch happens to be today.

/** ACCESS_SOURCE_URL is where the Corresponding Source is published. */
export const ACCESS_SOURCE_URL = 'https://github.com/Psiphon-Inc/psiphon-access';

/**
 * ACCESS_REVISION is the revision this build was made from. A release build
 * passes the release tag, which the source URL resolves the same way it
 * resolves a commit. Any other build passes or derives a full commit.
 */
export const ACCESS_REVISION = 'v19.0.0-psiphon.1';

/**
 * ACCESS_BUILD is the human-readable build label: the nearest tag, the short
 * commit, and a -dirty suffix when the tree had uncommitted changes.
 */
export const ACCESS_BUILD = 'v19.0.0-psiphon.1';
